#!/bin/bash
# Auto-generated RL policy extractor script
# Generated for 1 RL policy result files

echo "Processing: rl_policy_8dc66ba9_4s_8a_40srv"
echo "  FLOW_ENDED/"
scavetool x --type v --filter "module(**.server[*].app[*]) AND \"flowEndedRequesterID:vector\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/FLOW_ENDED/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.vec
echo "  FLOW_STARTED/"
scavetool x --type v --filter "module(**.server[*].app[*]) AND \"flowStartedRequesterID:vector\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/FLOW_STARTED/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.vec
echo "  REQUEST_SENT/"
scavetool x --type v --filter "module(**.server[*].app[*]) AND \"requestSentRequesterID:vector\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/REQUEST_SENT/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.vec
echo "  REPLY_LENGTH_ASKED/"
scavetool x --type v --filter "module(**.server[*].app[*]) AND \"replyLengthAsked:vector\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/REPLY_LENGTH_ASKED/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.vec
echo "  REQUESTER_ID/"
scavetool x --type v --filter "module(**.**.relayUnit) AND \"RequesterID:vector\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/REQUESTER_ID/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.vec
echo "  QUEUE_LEN/"
scavetool x --type v --filter "module(**.**.eth[*].mac.queue) AND \"queueLength:vector\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/QUEUE_LEN/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.vec
echo "  PACKET_ACTION/"
scavetool x --type v --filter "module(**.**.relayUnit) AND \"packetAction:vector\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/PACKET_ACTION/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.vec
echo "  SYN_SENT/"
scavetool x --type v --filter "module(**.server[*].tcp) AND \"tcpConnectionSYNSent:vector\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/SYN_SENT/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.vec
echo "  SYN_SENT_IS_BURSTY/"
scavetool x --type v --filter "module(**.server[*].tcp) AND \"tcpConnectionSYNSentIsBursty:vector\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/SYN_SENT_IS_BURSTY/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.vec
echo "  FIN_ACK_RCV/"
scavetool x --type v --filter "module(**.server[*].tcp) AND \"tcpConnectionFINRcv:vector\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/FIN_ACK_RCV/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.vec
echo "  OOO_SEG_NUM/"
scavetool x --type s --filter "module(**.server[*].tcp) AND \"numReceivedOOOSegs\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/OOO_SEG_NUM/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.sca
echo "  UTILIZATION/"
scavetool x --type s --filter "module(**.**.eth[*].mac) AND \"bits/sec *\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/UTILIZATION/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.sca
echo "  PER_PACKET_FABRIC_DELAY_COUNTS/"
scavetool x --type s --filter "module(**.**.eth[*].mac) AND \"perPacketFabricDelayNum\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/PER_PACKET_FABRIC_DELAY_COUNTS/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.sca
echo "  PER_PACKET_FABRIC_DELAY_SUM/"
scavetool x --type s --filter "module(**.**.eth[*].mac) AND \"perPacketFabricDelaySum\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/PER_PACKET_FABRIC_DELAY_SUM/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.sca
echo "  V2_RCVD_SOONER/"
scavetool x --type s --filter "module(**.ipv4.ip) AND \"v2RcvdSoonerStored\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/V2_RCVD_SOONER/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.sca
echo "  V2_RCVD_CORRECTLY/"
scavetool x --type s --filter "module(**.ipv4.ip) AND \"v2RcvdCorrectlyPushed\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/V2_RCVD_CORRECTLY/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.sca
echo "  V2_RCVD_LATER/"
scavetool x --type s --filter "module(**.ipv4.ip) AND \"v2RcvdLaterPushed\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/V2_RCVD_LATER/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.sca
echo "  NUM_MARKING_TIMEOUTS/"
scavetool x --type s --filter "module(**.ipv4.ip) AND \"numTimeoutsMarking\"" -o /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims/extracted_results/NUM_MARKING_TIMEOUTS/rl_policy_8dc66ba9_4s_8a_40srv_rl_policy.csv -F CSV-S 4_spines_8_aggs_40_servers_1_burstyapps_1_mice_40_reqPerBurst_11.85_bgintermult_1_bgfsizemult_0.11_burstyintermult_1_burstyfsizemult_250_ttl_0_rep_2_rndfwfactor_2_rndbouncefactor_20000_incastfsize_0.00120_mrktimer_0.00120_ordtimer_rl_policy.sca

echo "RL policy extraction completed!"
