#!/bin/bash

# Process threshold datasets generated by DCTCP_SD_THRESHOLD_VARIATION
# Creates individual datasets and combines them with threshold as feature

echo "===================================================================="
echo "Processing Threshold Datasets"
echo "===================================================================="

cd /home/ubuntu/practical_deflection/Omnet_Sims/dc_simulations/simulations/sims

# Function to process one threshold
process_threshold() {
    local threshold=$1
    local threshold_dir="results/threshold_${threshold}"
    
    echo "--------------------------------------------------------------------"
    echo "Processing threshold: $threshold"
    echo "--------------------------------------------------------------------"
    
    if [ ! -d "$threshold_dir" ]; then
        echo "✗ Directory $threshold_dir not found"
        return 1
    fi
    
    # Clean previous processing
    rm -rf extracted_results results_1G
    
    # Create temporary results directory with expected structure
    mkdir -p results
    
    # Copy files to results directory (removing threshold suffix)
    for file in "$threshold_dir"/*; do
        if [ -f "$file" ]; then
            filename=$(basename "$file")
            # Remove threshold suffix from filename
            new_filename=$(echo "$filename" | sed "s/_threshold_${threshold}//g")
            cp "$file" "results/$new_filename"
        fi
    done
    
    echo "Extracting data for threshold $threshold..."
    
    # Extract data using existing pipeline
    python3 ./extractor_shell_creator.py dctcp_sd
    
    # Check if extraction was successful
    if [ -d "results" ]; then
        pushd results
        if [ -f "extractor.sh" ]; then
            bash extractor.sh
        else
            echo "✗ extractor.sh not found"
            popd
            return 1
        fi
        popd
        
        # Move extracted results
        if [ -d "extracted_results" ]; then
            mv extracted_results results_1G
        else
            echo "✗ extracted_results not found"
            return 1
        fi
        
        echo "Creating dataset for threshold $threshold..."
        
        # Create dataset
        python3 create_dataset.py
        
        if [ -f "dataset.csv" ]; then
            # Add threshold column to the dataset
            python3 -c "
import pandas as pd
df = pd.read_csv('dataset.csv')
df['deflection_threshold'] = $threshold
df.to_csv('threshold_dataset_${threshold}.csv', index=False)
print(f'✓ Created threshold_dataset_${threshold}.csv with {len(df)} rows')
"
            # Clean up intermediate files
            rm -f dataset.csv
            echo "✓ Successfully processed threshold $threshold"
            return 0
        else
            echo "✗ dataset.csv not created for threshold $threshold"
            return 1
        fi
    else
        echo "✗ Results directory not found"
        return 1
    fi
}

# Process all thresholds
thresholds=(0.3 0.5 0.7 0.9)
successful_thresholds=()

for threshold in "${thresholds[@]}"; do
    if process_threshold "$threshold"; then
        successful_thresholds+=("$threshold")
    fi
done

echo ""
echo "===================================================================="
echo "Combining Threshold Datasets"
echo "===================================================================="

if [ ${#successful_thresholds[@]} -gt 0 ]; then
    echo "Successfully processed thresholds: ${successful_thresholds[*]}"
    
    # Combine all threshold datasets
    python3 -c "
import pandas as pd
import glob

# Find all threshold dataset files
threshold_files = glob.glob('threshold_dataset_*.csv')
print(f'Found threshold datasets: {threshold_files}')

if threshold_files:
    # Load and combine all datasets
    dfs = []
    for file in sorted(threshold_files):
        df = pd.read_csv(file)
        threshold = file.split('_')[-1].replace('.csv', '')
        print(f'Loaded {len(df)} rows for threshold {threshold}')
        dfs.append(df)
    
    # Combine all dataframes
    combined_df = pd.concat(dfs, ignore_index=True)
    
    # Reorder columns to put deflection_threshold early
    cols = combined_df.columns.tolist()
    if 'deflection_threshold' in cols:
        cols.remove('deflection_threshold')
        # Insert deflection_threshold after time if it exists
        if 'time' in cols:
            time_idx = cols.index('time')
            cols.insert(time_idx + 1, 'deflection_threshold')
        else:
            cols.insert(0, 'deflection_threshold')
        combined_df = combined_df[cols]
    
    # Save combined dataset
    combined_df.to_csv('threshold_dataset_combined.csv', index=False)
    
    print(f'\\n✓ Combined dataset saved: threshold_dataset_combined.csv')
    print(f'Total rows: {len(combined_df)}')
    print(f'Columns: {list(combined_df.columns)}')
    print(f'\\nThreshold distribution:')
    print(combined_df['deflection_threshold'].value_counts().sort_index())
    
    # Show sample
    print(f'\\nSample data (first 5 rows):')
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', None)
    print(combined_df.head())
else:
    print('No threshold datasets found to combine')
"
    
    # Clean up individual threshold files
    rm -f threshold_dataset_*.csv
    
    echo ""
    echo "===================================================================="
    echo "Final Dataset Ready"
    echo "===================================================================="
    
    if [ -f "threshold_dataset_combined.csv" ]; then
        echo "✓ Final dataset: threshold_dataset_combined.csv"
        echo "Dataset info:"
        echo "Lines: $(wc -l < threshold_dataset_combined.csv)"
        echo "Columns: $(head -1 threshold_dataset_combined.csv | tr ',' '\n' | wc -l)"
    else
        echo "✗ Final combined dataset not created"
    fi
    
else
    echo "✗ No thresholds were successfully processed"
    exit 1
fi

echo ""
echo "===================================================================="
echo "Processing Complete!"
echo "===================================================================="
